# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
DEFAULT_USER_IMAGE_URL = "http://res.cloudinary.com/gmkohler/image/upload/v1444792510/Poodle_kqgsbm.png"
DEFAULT_USER_COVER_IMAGE_URL = "http://res.cloudinary.com/gmkohler/image/upload/v1444792510/Poodle_kqgsbm.png"
DEFAULT_SONG_IMAGE_URL = "http://res.cloudinary.com/gmkohler/image/upload/v1444793208/snoopy_hw9q5n.gif"
User.create([{email: "snoopy@example.com",
                username:"snoopy",
                location:"doghouse",
                bio: "zzzzzzzzzz"
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445906796/e7af5a51ea0bcf7dd285450b5ae91337_gr5hme.jpg",
                cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/c_crop,g_south,h_260,w_960,y_195/v1445907232/snoopy-wallpaper-2_ad2bzn.jpg",
                password: "snoopy"},
             {email: "human@example.com",
                username: "human",
                location: "San Francisco",
                bio: "Some ruff demos of what's to come",
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/c_crop,g_south_west,h_270/v1445897696/md04_x4zkbf.jpg",
                cover_image_url: DEFAULT_COVER_IMAGE_URL
                password: "humanhuman"},
             {email: "corgi@example.com",
                username: "majestic_corgi",
                location: "Field of Dreams",
                bio: "arrrruuuuffff!! ruff ruff!!",
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/c_crop,w_1583,x_350,y_320/v1445899622/MWBJlst_mhbw6r.jpg",
                cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/c_scale,w_1708/v1445900700/1KH_3724_SE_dgcyoa.jpg",
                password: "corgicorgi"},
             {email: "poodle@example.com",
                username: "puddles_12",
                location: "a puddle of joy",
                bio: "arf woof ruff! ruff ruff woof arf woof arruf!",
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445901633/natty_agk3v7.jpg",
                cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445902036/2doug1203_kn2uju.jpg",
                password: "poodlepoodle"},
             {email: "doge@example.com",
                username: "doge",
                location: "such unsure",
                bio: "wow. many music. much listen. so bark.",
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445902267/3f5a00acf72df93528b6bb7cd0a4fd0c_stnvbe.jpg",
                cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445902503/18361-doge-follow-your-dreams_tg4nac.jpg",
                password:"dogedoge"},
             {email: "airbud@example.com",
               username:"under_dogg",
               location: "Hall of Fame",
               bio: "You miss 100% of the cats you don't chase."},
               image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445907602/tobby_le_frappeur_etoile_vf_wt_poster_49123_taoddj.jpg",
               cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445907531/Air_Bud_Header_cyurgu.jpg",
               password:"airbudairbud"
             },
             {email:"bo@example.com",
                username:"first_pup",
                location:"1600 Pennsylvania Ave NW",
                bio:"Gonna miss this yard",
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445907909/Bo_official_portrait_pplrcd.jpg",
                cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/c_scale,w_1112/v1445908031/White_House_Washington_tewyo4.jpg",
                password:"boobama"
            },
            {email:"clifford@example.com",
               username:"big_red",
               location:"Everywhere",
               bio:"arrfff ruff wooff arrff bark bark woof!",
               image_url:"http://res.cloudinary.com/gmkohler/image/upload/v1445908437/clifford_main_image_wg6sre.jpg",
               cover_image_url: "http://res.cloudinary.com/gmkohler/image/upload/c_crop,h_260,w_960,x_222,y_2010/v1445908630/Clifford_prjhim.jpg",
               password:"cliffordclifford"
             },
             {email: "scooby@example.com",
                username:"scooby_doo",
                location: "avoiding work",
                bio: "roooby rack?",
                image_url: "http://res.cloudinary.com/gmkohler/image/upload/v1445909370/scooby_doo_2_mumwfn.jpg",
                cover_image_url: "",
                password: "scooby"},
             {email: "laika@example.com",
                username:"laika",
                location:"outer space",
                bio:"Moscow, we have a problem.",
                image_url:"http://res.cloudinary.com/gmkohler/image/upload/v1445909180/2678885-4063_o_laika_x9ojth.jpg",
                cover_image_url:"http://res.cloudinary.com/gmkohler/image/upload/v1445909229/outer-space-wallpaper-pictures_xt8rkp.jpg",
                password:"laikalaika"}
            ])
Song.create([{title: "Atomic Dog",
                content_url: 'http://res.cloudinary.com/gmkohler/video/upload/v1444944506/George_Clinton_-_Atomic_Dog_gziqae.mp3',
                image_url: DEFAULT_SONG_IMAGE_URL,
                artist_id: 2},
             {title: "Who Let the Dogs Out?",
                content_url: 'http://res.cloudinary.com/gmkohler/video/upload/v1444944599/Baha_Men_-_Who_Let_The_Dogs_Out_Original_version_-_Full_HD_-_1080p_zagtgq.mp3',
                image_url: DEFAULT_SONG_IMAGE_URL,
                artist_id: 2},
             {title: "Hounds of Love",
                content_url: 'http://res.cloudinary.com/gmkohler/video/upload/v1444944249/Kate_Bush_-_Hounds_of_Love_wdgudh.mp3',
                image_url: DEFAULT_SONG_IMAGE_URL,
                artist_id: 2},
             {title: "Ain't Nothin But a Hound Dog",
                content_url: 'http://res.cloudinary.com/gmkohler/video/upload/v1444944678/Elvis_Presley_-_Hound_Dog_kd8ety.mp3',
                image_url: DEFAULT_SONG_IMAGE_URL,
                artist_id: 2},
             {title: "Scooby Scooby Doo (Where Are You?)",
                content_url: 'http://res.cloudinary.com/gmkohler/video/upload/v1444944735/Scooby_Doo_Theme_Song_jg9u8a.mp3',
                image_url: DEFAULT_SONG_IMAGE_URL,
                artist_id: 9}
            ])
